/**
 * \file mbedtls_config_optimized.h
 *
 * \brief Optimized configuration for SSH use only
 *
 * Based on the default config but with SSL/TLS and X.509 features disabled
 * to reduce binary size while keeping SSH functionality intact.
 */

/* Copy the working config and add our optimizations on top */
#include "mbedtls_config.h"

/* 
 * DISABLE SSL/TLS FEATURES (not needed for SSH)
 */
#ifdef MBEDTLS_SSL_CLI_C
#undef MBEDTLS_SSL_CLI_C
#endif

#ifdef MBEDTLS_SSL_SRV_C
#undef MBEDTLS_SSL_SRV_C
#endif

#ifdef MBEDTLS_SSL_TLS_C
#undef MBEDTLS_SSL_TLS_C
#endif

#ifdef MBEDTLS_SSL_PROTO_TLS1_2
#undef MBEDTLS_SSL_PROTO_TLS1_2
#endif

#ifdef MBEDTLS_SSL_PROTO_TLS1_3
#undef MBEDTLS_SSL_PROTO_TLS1_3
#endif

#ifdef MBEDTLS_SSL_PROTO_DTLS
#undef MBEDTLS_SSL_PROTO_DTLS
#endif

#ifdef MBEDTLS_SSL_CACHE_C
#undef MBEDTLS_SSL_CACHE_C
#endif

#ifdef MBEDTLS_SSL_COOKIE_C
#undef MBEDTLS_SSL_COOKIE_C
#endif

#ifdef MBEDTLS_SSL_TICKET_C
#undef MBEDTLS_SSL_TICKET_C
#endif

/*
 * DISABLE X.509 CERTIFICATE HANDLING (not needed for SSH)
 */
#ifdef MBEDTLS_X509_USE_C
#undef MBEDTLS_X509_USE_C
#endif

#ifdef MBEDTLS_X509_CRT_PARSE_C
#undef MBEDTLS_X509_CRT_PARSE_C
#endif

#ifdef MBEDTLS_X509_CRL_PARSE_C
#undef MBEDTLS_X509_CRL_PARSE_C
#endif

#ifdef MBEDTLS_X509_CSR_PARSE_C
#undef MBEDTLS_X509_CSR_PARSE_C
#endif

#ifdef MBEDTLS_X509_CREATE_C
#undef MBEDTLS_X509_CREATE_C
#endif

#ifdef MBEDTLS_X509_CRT_WRITE_C
#undef MBEDTLS_X509_CRT_WRITE_C
#endif

#ifdef MBEDTLS_X509_CSR_WRITE_C
#undef MBEDTLS_X509_CSR_WRITE_C
#endif

#ifdef MBEDTLS_X509_CHECK_KEY_USAGE
#undef MBEDTLS_X509_CHECK_KEY_USAGE
#endif

#ifdef MBEDTLS_X509_CHECK_EXTENDED_KEY_USAGE
#undef MBEDTLS_X509_CHECK_EXTENDED_KEY_USAGE
#endif

#ifdef MBEDTLS_X509_RSASSA_PSS_SUPPORT
#undef MBEDTLS_X509_RSASSA_PSS_SUPPORT
#endif

/*
 * DISABLE PEM/DER FORMAT PARSING (use raw key formats for SSH)
 */
#ifdef MBEDTLS_PEM_PARSE_C
#undef MBEDTLS_PEM_PARSE_C
#endif

#ifdef MBEDTLS_PEM_WRITE_C
#undef MBEDTLS_PEM_WRITE_C
#endif

#ifdef MBEDTLS_BASE64_C
#undef MBEDTLS_BASE64_C
#endif

/*
 * DISABLE PKCS#5, PKCS#12, PKCS#7 (not used by SSH)
 * Keep PKCS#1 v1.5 which is needed for RSA
 */
#ifdef MBEDTLS_PKCS5_C
#undef MBEDTLS_PKCS5_C
#endif

#ifdef MBEDTLS_PKCS12_C
#undef MBEDTLS_PKCS12_C
#endif

#ifdef MBEDTLS_PKCS7_C
#undef MBEDTLS_PKCS7_C
#endif

/* Keep PKCS1_V15 - needed for RSA in SSH */
/* #ifdef MBEDTLS_PKCS1_V15
#undef MBEDTLS_PKCS1_V15
#endif *//*
 * DISABLE PKCS FEATURES NOT NEEDED FOR SSH
 */
#ifdef MBEDTLS_PKCS5_C
#undef MBEDTLS_PKCS5_C
#endif

#ifdef MBEDTLS_PKCS7_C
#undef MBEDTLS_PKCS7_C
#endif

#ifdef MBEDTLS_PKCS12_C
#undef MBEDTLS_PKCS12_C
#endif

/*
 * DISABLE UNUSED CRYPTO ALGORITHMS
 */
#ifdef MBEDTLS_ARIA_C
#undef MBEDTLS_ARIA_C
#endif

#ifdef MBEDTLS_BLOWFISH_C
#undef MBEDTLS_BLOWFISH_C
#endif

#ifdef MBEDTLS_CAMELLIA_C
#undef MBEDTLS_CAMELLIA_C
#endif

#ifdef MBEDTLS_DES_C
#undef MBEDTLS_DES_C
#endif

#ifdef MBEDTLS_RIPEMD160_C
#undef MBEDTLS_RIPEMD160_C
#endif

#ifdef MBEDTLS_SHA3_C
#undef MBEDTLS_SHA3_C
#endif

/*
 * DISABLE PSA CRYPTO (keep legacy API for SSH)
 */
#ifdef MBEDTLS_PSA_CRYPTO_C
#undef MBEDTLS_PSA_CRYPTO_C
#endif

#ifdef MBEDTLS_PSA_CRYPTO_SE_C
#undef MBEDTLS_PSA_CRYPTO_SE_C
#endif

#ifdef MBEDTLS_PSA_CRYPTO_STORAGE_C
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C
#endif

#ifdef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_PSA_ITS_FILE_C
#endif

/*
 * DISABLE FEATURES THAT DEPEND ON PSA CRYPTO
 */
#ifdef MBEDTLS_LMS_C
#undef MBEDTLS_LMS_C
#endif

#ifdef MBEDTLS_LMOTS_C
#undef MBEDTLS_LMOTS_C
#endif

/*
 * DISABLE SSL-RELATED FEATURES THAT HAVE DEPENDENCIES
 */
#ifdef MBEDTLS_SSL_SESSION_TICKETS
#undef MBEDTLS_SSL_SESSION_TICKETS
#endif

#ifdef MBEDTLS_SSL_SERVER_NAME_INDICATION
#undef MBEDTLS_SSL_SERVER_NAME_INDICATION
#endif

#ifdef MBEDTLS_SSL_ALPN
#undef MBEDTLS_SSL_ALPN
#endif

#ifdef MBEDTLS_SSL_DTLS_ANTI_REPLAY
#undef MBEDTLS_SSL_DTLS_ANTI_REPLAY
#endif

#ifdef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#undef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#endif

#ifdef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#undef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#endif

#ifdef MBEDTLS_SSL_DTLS_CONNECTION_ID
#undef MBEDTLS_SSL_DTLS_CONNECTION_ID
#endif

#ifdef MBEDTLS_SSL_ALL_ALERT_MESSAGES
#undef MBEDTLS_SSL_ALL_ALERT_MESSAGES
#endif

#ifdef MBEDTLS_SSL_CONTEXT_SERIALIZATION
#undef MBEDTLS_SSL_CONTEXT_SERIALIZATION
#endif

#ifdef MBEDTLS_SSL_ENCRYPT_THEN_MAC
#undef MBEDTLS_SSL_ENCRYPT_THEN_MAC
#endif

#ifdef MBEDTLS_SSL_EXTENDED_MASTER_SECRET
#undef MBEDTLS_SSL_EXTENDED_MASTER_SECRET
#endif

#ifdef MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#undef MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#endif

#ifdef MBEDTLS_SSL_KEYING_MATERIAL_EXPORT
#undef MBEDTLS_SSL_KEYING_MATERIAL_EXPORT
#endif

#ifdef MBEDTLS_SSL_RENEGOTIATION
#undef MBEDTLS_SSL_RENEGOTIATION
#endif

#ifdef MBEDTLS_SSL_MAX_FRAGMENT_LENGTH
#undef MBEDTLS_SSL_MAX_FRAGMENT_LENGTH
#endif

#ifdef MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
#undef MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
#endif

#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_ENABLED
#endif

#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#endif

#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
#endif

/*
 * PLATFORM-SPECIFIC SETTINGS FOR ESP32
 */

/* Disable platform entropy sources - ESP32 has its own entropy */
#ifndef MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_NO_PLATFORM_ENTROPY
#endif

/* Disable platform time functions - not available on ESP32 */
#ifdef MBEDTLS_HAVE_TIME
#undef MBEDTLS_HAVE_TIME
#endif

#ifdef MBEDTLS_HAVE_TIME_DATE
#undef MBEDTLS_HAVE_TIME_DATE
#endif
